channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pip=22.1.2
  - nodejs=16.4.2
  - pip:
      - robotframework-browser==14.2.1
      - rpaframework==19.4.1
      - rpadriver==1.2.1
      - pandas==1.5.2
      - openpyxl==3.0.10
      - requests==2.28.1
rccPostInstall:
  - rfbrowser init